-- H2 2.4.240;
;             
CREATE USER IF NOT EXISTS "SA" SALT '3a90b05e097d1bfe' HASH '809998ccc6136e248623c1ca59f67c4c2427e754e506a99744a8cf360b2032d7' ADMIN;         
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "USER_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 34) NOT NULL,
    "USERNAME" CHARACTER VARYING(50) NOT NULL,
    "PASSWORD" CHARACTER VARYING(100) NOT NULL,
    "NAME" CHARACTER VARYING(30) NOT NULL,
    "EMAIL" CHARACTER VARYING(100) NOT NULL,
    "HP" CHARACTER VARYING(20),
    "ADDRESS" CHARACTER VARYING(255),
    "ROLE" CHARACTER VARYING(20) DEFAULT 'USER' NOT NULL,
    "REG_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);    
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("USER_ID");   
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
INSERT INTO "PUBLIC"."USERS" VALUES
(1, 'admin', '1234', 'Admin', 'admin@azabook.com', '010-1111-1111', 'Seoul', 'ADMIN', TIMESTAMP '2026-03-26 01:29:25.980157'),
(2, 'user1', '1234', 'User One', 'user1@azabook.com', '010-2222-2222', 'Busan', 'USER', TIMESTAMP '2026-03-26 01:29:25.982161');         
CREATE CACHED TABLE "PUBLIC"."ORDERS"(
    "ORDER_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "USER_ID" BIGINT,
    "ORDER_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ORDER_STATUS" INTEGER DEFAULT 0,
    "TOTAL_PRICE" INTEGER,
    "RECEIVER_NAME" CHARACTER VARYING(50),
    "RECEIVER_HP" CHARACTER VARYING(50),
    "DELIVERY_ADDRESS" CHARACTER VARYING(255),
    "DELIVERY_DETAIL_ADDRESS" CHARACTER VARYING(255)
);       
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ORDER_ID"); 
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.ORDERS;  
INSERT INTO "PUBLIC"."ORDERS" VALUES
(123, 2, TIMESTAMP '2026-03-26 07:54:36.106878', 0, 30000, U&'\d14c\c2a4\d2b8\c720\c800', '010-1111-2222', U&'\c11c\c6b8\c2dc \c5b4\b518\ac00', U&'101\d638'),
(777, 1, TIMESTAMP '2026-03-26 08:22:27.239386', 1, 65000, U&'\b2e4\b3c5\c655', '010-7777-7777', U&'\b3c4\c11c\ad00\ae38 7', U&'3\ce35'),
(999, 2, TIMESTAMP '2026-03-26 07:53:18.334193', 0, 20000, U&'\d14c\c2a4\d2b8\c720\c800', '010-1111-2222', U&'\c11c\c6b8\c2dc \c5b4\b518\ac00', U&'101\d638'),
(1000, 33, TIMESTAMP '2026-03-26 07:59:30.960816', 4, 45000, U&'\d64d\ae38\b3d9', '010-9999-8888', U&'\bd80\c0b0\ad11\c5ed\c2dc', U&'202\d638');             
CREATE CACHED TABLE "PUBLIC"."BOOKS"(
    "ISBN" CHARACTER VARYING,
    "BOOK_NAME" CHARACTER VARYING,
    "AUTHOR" CHARACTER VARYING,
    "PUBLISHER" CHARACTER VARYING,
    "PUBLICATION_DATE" CHARACTER VARYING,
    "PRICE" CHARACTER VARYING,
    "STOCK" CHARACTER VARYING,
    "CATEGORY_ID" CHARACTER VARYING,
    "IMG_LINK" CHARACTER VARYING,
    "DESCRIPTION" CHARACTER VARYING,
    "RANK_NUM" CHARACTER VARYING,
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 31) NOT NULL
);      
-- 30 +/- SELECT COUNT(*) FROM PUBLIC.BOOKS;  
INSERT INTO "PUBLIC"."BOOKS" VALUES
('9791171715503', U&'\c8fd\c740 \c655\b140\b97c \c704\d55c \d30c\bc18\b290 (\c591\c7a5 \d2b9\bcc4\d310)', U&'\bc15\bbfc\addc \c9c0\c74c', U&'\c704\c988\b364\d558\c6b0\c2a4', '2025-11-19', '20000', '10', '1', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788959133918.jpg', U&'\c18c\c124/\c2dc/\d76c\ace1', '1', 1),
('9791194530701', U&'\ad34\d14c\b294 \baa8\b4e0 \ac83\c744 \b9d0\d588\b2e4', U&'\c2a4\c988\d0a4 \c720\c774 \c9c0\c74c, \c774\c9c0\c218 \c62e\ae40', U&'\b9ac\d504', '2025-11-18', '17000', '10', '1', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791194530701.jpg', U&'\c18c\c124/\c2dc/\d76c\ace1', '2', 2),
('9791199496651', U&'\bd80\cc98\b2d8 \b9d0\c500\b300\b85c \c0b4\c544\bcf4\b2c8', U&'\d1a0\b2c8 \d398\b974\b09c\b3c4 \c9c0\c74c, \ac15\c815\c120 \c62e\ae40', U&'\c70c\b9c8', '2026-02-20', '18900', '10', '2', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791199496651.jpg', U&'\c790\ae30\acc4\bc1c', '3', 3),
('9791173576577', U&'\c9c4\bcf4\b97c \c704\d55c \c8fc\c2dd\d22c\c790', U&'\c774\ad11\c218 \c9c0\c74c', U&'21\c138\ae30\bd81\c2a4', '2025-12-17', '22000', '10', '3', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791173576577.jpg', U&'\acbd\c81c\acbd\c601', '4', 4),
('9791193904671', U&'\b3c8\c758 \bc29\c815\c2dd', U&'\baa8\ac74 \d558\c6b0\c808 \c9c0\c74c, \bc15\c601\c900 \c62e\ae40', U&'\c11c\c0bc\b3c5', '2026-01-16', '28000', '10', '3', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193904671.jpg', U&'\acbd\c81c\acbd\c601', '5', 5),
('9788954799355', U&'EBS \c655\cd08\bcf4 \c601\c5b4 (2026 \c0c1\d3b8)', U&'\b9c8\c2a4\d130\c720\c9c4 \c9c0\c74c', U&'\d55c\ad6d\ad50\c721\bc29\c1a1\acf5\c0ac(\ae30\d0c0)', '2026-02-20', '16000', '10', '4', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788954799355.jpg', U&'\c678\ad6d\c5b4', '6', 6),
('9791124248171', U&'\c778\c0dd\c744 \c704\d55c \cd5c\c18c\d55c\c758 \c0dd\ac01', U&'\c2e0\c601\c900.\ace0\c601\c131 \c9c0\c74c', U&'\c0c1\c0c1\c2a4\d018\c5b4', '2026-02-25', '19800', '10', '5', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791124248171.jpg', U&'\c778\bb38\d559', '7', 7),
('9788937460586', U&'\c2ef\b2e4\b974\d0c0', U&'\d5e4\b974\b9cc \d5e4\c138 \c9c0\c74c, \bc15\bcd1\b355 \c62e\ae40', U&'\bbfc\c74c\c0ac', '2002-01-20', '8000', '10', '1', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788937460586.jpg', U&'\c18c\c124/\c2dc/\d76c\ace1', '8', 8),
('9788998441012', U&'\baa8\c21c', U&'\c591\adc0\c790 \c9c0\c74c', U&'\c4f0\b2e4', '2013-04-01', '13000', '10', '1', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788998441012.jpg', U&'\c18c\c124/\c2dc/\d76c\ace1', '9', 9),
('9791142816383', U&'\baa8\baa8\c138 \c544\d0a4\b77c\c758 \ccab\c0ac\b791 \d30c\d0c4 \c911 4 (\d2b8\b9ac\d50c \d2b9\c804\d310)', U&'\d558\b808\ce74\c640 \c2e0\d0c0 \c9c0\c74c, \c774\c18c\c5f0 \c62e\ae40', U&'\c11c\c6b8\bbf8\b514\c5b4\cf54\bbf9\c2a4(\c11c\c6b8\bb38\d654\c0ac)', '2026-02-27', '7500', '10', '6', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791142816383.jpg', U&'\b9cc\d654/\b77c\c774\d2b8\b178\bca8', '10', 10),
('9791141602376', U&'\c548\b155\c774\b77c \adf8\b7ac\c5b4', U&'\ae40\c560\b780 \c9c0\c74c', U&'\bb38\d559\b3d9\b124', '2025-06-20', '16800', '10', '1', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791141602376.jpg', U&'\c18c\c124/\c2dc/\d76c\ace1', '11', 11),
('9788925569871', U&'\d638\c18c\b2e4 \b9c8\baa8\b8e8\b77c\b294 \c138\acc4', U&'\cc30\c2a4 \c194\b85c\baac \c9c0\c74c, \ae40\c9c0\c724 \c62e\ae40', U&'\c54c\c5d0\c774\ce58\cf54\b9ac\c544(RHK)', '2026-02-27', '33000', '10', '7', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788925569871.jpg', U&'\c608\c220/\b300\c911\bb38\d654', '12', 12),
('9791168342941', U&'\bc15\acf0\d76c \c5f0\ae08 \bd80\c790 \c218\c5c5', U&'\bc15\acf0\d76c \c9c0\c74c', U&'\c778\d50c\b8e8\c5d4\c15c(\c8fc)', '2025-06-25', '21000', '10', '3', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791168342941.jpg', U&'\acbd\c81c\acbd\c601', '13', 13),
('9791142816543', U&'\bc18\b527\bd88\c774\c758 \d63c\b840 9', U&'\d0c0\ce58\bc14\b098 \c624\b808\cf54 \c9c0\c74c, \c720\c720\b9ac \c62e\ae40', U&'\c11c\c6b8\bbf8\b514\c5b4\cf54\bbf9\c2a4(\c11c\c6b8\bb38\d654\c0ac)', '2026-02-26', '8500', '10', '6', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791142816543.jpg', U&'\b9cc\d654/\b77c\c774\d2b8\b178\bca8', '14', 14);        
INSERT INTO "PUBLIC"."BOOKS" VALUES
('9791193282533', U&'\c790\bcf8\c8fc\c758 \c2dc\b300\c5d0\c11c \c0b4\c544\b0a8\ae30 \c704\d55c \cd5c\c18c\d55c\c758 \acbd\c81c \acf5\bd80', U&'\bc31\c5b5\b0a8(\ae40\c6b1\d604) \c9c0\c74c', U&'\d558\c774\c2a4\d2b8', '2025-12-04', '28000', '10', '3', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193282533.jpg', U&'\acbd\c81c\acbd\c601', '15', 15),
('9788936439743', U&'\d63c\baa8\b178', U&'\c131\d574\b098 \c9c0\c74c', U&'\cc3d\be44', '2025-03-28', '18000', '10', '1', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788936439743.jpg', U&'\c18c\c124/\c2dc/\d76c\ace1', '16', 16),
('9788917243802', U&'ETS \d1a0\c775 \c815\ae30\c2dc\d5d8 \ae30\cd9c\bb38\c81c\c9d1 1000 Vol. 5 Reading (\b9ac\b529)', U&'ETS \c9c0\c74c', U&'(\c8fc)YBM(\c640\c774\be44\c5e0)', '2025-12-15', '22000', '10', '4', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788917243802.jpg', U&'\c678\ad6d\c5b4', '17', 17),
('9791193941577', U&'\b1cc\b294 \c5b4\b5bb\ac8c \b098\b97c \c870\c885\d558\b294\ac00', U&'\d06c\b9ac\c2a4 \b098\c774\bc14\c6b0\c5b4 \c9c0\c74c, \ae40\c724\c885 \c62e\ae40', U&'\d074\b7a9\bd81\c2a4', '2026-01-21', '18800', '10', '8', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791193941577.jpg', U&'\acfc\d559', '18', 18),
('9791138934428', U&'2026 \d070\bcc4\c324 \cd5c\d0dc\c131\c758 \bcc4\2605\bcc4\d55c\ad6d\c0ac \d55c\ad6d\c0ac\b2a5\b825\ac80\c815\c2dc\d5d8 \c2ec\d654(1, 2, 3\ae09) \c0c1', U&'\cd5c\d0dc\c131 \c9c0\c74c', U&'\c774\d22c\c2a4\bd81', '2025-12-09', '19000', '10', '9', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791138934428.jpg', U&'\c218\d5d8\c11c/\c790\aca9\c99d', '19', 19),
('9791194368854', U&'\ae40\c7ac\c6b0\c758 \ae30\bcf8 \b3d9\c0ac 100', U&'\ae40\c7ac\c6b0 \c9c0\c74c', U&'\c0c1\c0c1\c2a4\d018\c5b4', '2025-12-10', '22000', '10', '4', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791194368854.jpg', U&'\c678\ad6d\c5b4', '20', 20),
('9791169665438', U&'2026 \bb38\b3d9\ade0 \d55c\ad6d\c0ac D-30 \bb38\b2e8\c18d \baa8\c758\ace0\c0ac', U&'\bb38\b3d9\ade0 \c9c0\c74c', U&'\c5d0\c2a4\d2f0\c720\b2c8\d0c0\c2a4', '2026-02-27', '16000', '10', '9', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791169665438.jpg', U&'\c218\d5d8\c11c/\c790\aca9\c99d', '21', 21),
('9791130675275', U&'\c815\b2f5\c740 \c788\b2e4', U&'\c774\c815\d6a8 \c9c0\c74c', U&'\b2e4\c0b0\bd81\c2a4', '2026-02-23', '18000', '10', '10', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791130675275.jpg', U&'\c5d0\c138\c774', '22', 22),
('9791142344152', U&'\c0ac\ce74\baa8\d1a0 \b370\c774\c988 25 (\b354\be14 \d2b9\c804\d310)', U&'\c2a4\c988\d0a4 \c720\c6b0\d1a0 \c9c0\c74c', U&'\b300\c6d0\c528\c544\c774(\b9cc\d654)', '2026-02-27', '6500', '10', '6', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791142344152.jpg', U&'\b9cc\d654/\b77c\c774\d2b8\b178\bca8', '23', 23),
('9788917243796', U&'ETS \d1a0\c775 \c815\ae30\c2dc\d5d8 \ae30\cd9c\bb38\c81c\c9d1 1000 Vol. 5 Listening (\b9ac\c2a4\b2dd)', U&'ETS \c5ee\c74c', U&'(\c8fc)YBM(\c640\c774\be44\c5e0)', '2025-12-15', '22000', '10', '4', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788917243796.jpg', U&'\c678\ad6d\c5b4', '24', 24),
('9791138934442', U&'2026 \d070\bcc4\c324 \cd5c\d0dc\c131\c758 \bcc4\2605\bcc4\d55c\ad6d\c0ac \d55c\ad6d\c0ac\b2a5\b825\ac80\c815\c2dc\d5d8 \c2ec\d654(1, 2, 3\ae09) \d558', U&'\cd5c\d0dc\c131 \c9c0\c74c', U&'\c774\d22c\c2a4\bd81', '2025-12-09', '18500', '10', '9', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791138934442.jpg', U&'\c218\d5d8\c11c/\c790\aca9\c99d', '25', 25),
('9788925588735', U&'\d504\b85c\c81d\d2b8 \d5e4\c77c\ba54\b9ac (\c601\d654 \d2b9\bcc4\d310)', U&'\c564\b514 \c704\c5b4 \c9c0\c74c, \ac15\b3d9\d601 \c62e\ae40', U&'\c54c\c5d0\c774\ce58\cf54\b9ac\c544(RHK)', '2026-02-19', '22000', '10', '1', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9788925588735.jpg', U&'\c18c\c124/\c2dc/\d76c\ace1', '26', 26),
('9791163462071', U&'\b2e8\b2e8\b825', U&'\c774\c885\b300\c655 \c9c0\c74c, \ae40\cc38\c678 \adf8\b9bc', U&'\d14c\d06c\be4c\ad50\c721', '2026-03-01', '17000', '10', '11', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791163462071.jpg', U&'\c0ac\d68c\acfc\d559', '27', 27);            
INSERT INTO "PUBLIC"."BOOKS" VALUES
('9791199305304', U&'\c790\babd\c0b4\ad6c\d074\b7fd', U&'\d55c\b85c\b85c (HANRORO) \c9c0\c74c', U&'\c5b4\c13c\d2f1', '2025-07-25', '12000', '10', '1', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791199305304.jpg', U&'\c18c\c124/\c2dc/\d76c\ace1', '28', 28),
('9791138489324', U&'\d559\c0dd\d68c\c5d0\b3c4 \ad6c\ba4d\c740 \c788\b2e4! 11', U&'\bb34\ce58\b9c8\b85c \c9c0\c74c, \c637\bb34 \c62e\ae40', U&'\321c\c18c\bbf8\bbf8\b514\c5b4', '2026-03-04', '7000', '10', '6', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791138489324.jpg', U&'\b9cc\d654/\b77c\c774\d2b8\b178\bca8', '29', 29),
('9791191521504', U&'\cf54\c2a4\d53c 1\b9cc \b125\c2a4\d2b8 \b808\bca8', U&'\bc15\c2dc\b3d9 \c9c0\c74c', U&'\c9c0\c640\c778', '2026-03-10', '22000', '10', '3', 'https://contents.kyobobook.co.kr/sih/fit-in/458x0/pdt/9791191521504.jpg', U&'\acbd\c81c\acbd\c601', '30', 30);         
CREATE CACHED TABLE "PUBLIC"."ORDER_ITEMS"(
    "ORDER_ITEM_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 4) NOT NULL,
    "ORDER_ID" BIGINT,
    "ISBN" CHARACTER VARYING(50),
    "QUANTITY" INTEGER,
    "ORDER_PRICE" INTEGER
);            
ALTER TABLE "PUBLIC"."ORDER_ITEMS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ORDER_ITEM_ID");       
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_ITEMS;             
INSERT INTO "PUBLIC"."ORDER_ITEMS" VALUES
(1, 777, '9791171715503', 1, 20000),
(2, 777, '9791194530701', 2, 30000),
(3, 777, '9788954799355', 1, 15000),
(999, 999, '9791171715503', 1, 20000),
(10001, 1000, '9791194530701', 2, 45000);
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" UNIQUE NULLS DISTINCT ("USERNAME");      
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D4" UNIQUE NULLS DISTINCT ("EMAIL");        
